CREATE DATABASE WORKOUTDATABASE

CREATE TABLE DANHMUC(
	ID_DANHMUC INT NOT NULL,
	TENDANHMUC NVARCHAR(50) NOT NULL,
	MOTADANHMUC NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_DANHMUC PRIMARY KEY (TENDANHMUC)
)

CREATE TABLE DOITUONG(
	ID_DOITUONG INT NOT NULL,
	TENDOITUONG NVARCHAR(50) NOT NULL,
	MOTADOITUONG NVARCHAR(200),
	CONSTRAINT PK_DOITUONG PRIMARY KEY (TENDOITUONG )
)
CREATE TABLE HINHANH(
	ID INT NOT NULL,
	HINHANH NVARCHAR(MAX) NOT NULL
)


CREATE TABLE BAITAP(
	ID_BAITAP INT NOT NULL PRIMARY KEY,
	TENBAITAP NVARCHAR(100) NOT NULL,
	TENDANHMUC NVARCHAR(50) NOT NULL,
	TENDOITUONG NVARCHAR(50) NOT NULL,
	HINHANH NVARCHAR(MAX) NOT NULL,
	MOTABAITAP NVARCHAR(MAX) NOT NULL,
	THOILUONG INT,
	LUONGCALOTIEUTHU INT,
	TACDUNG NVARCHAR(200),
	CONSTRAINT FK_TENDANHMUC_BT FOREIGN KEY (TENDANHMUC) REFERENCES DANHMUC (TENDANHMUC),
	CONSTRAINT FK_TENDOITUONG_BT FOREIGN KEY (TENDOITUONG) REFERENCES DOITUONG (TENDOITUONG),
)

--GET TAT CA--

CREATE PROC PROC_GetAllBaiTap
AS 
SELECT * FROM BAITAP

CREATE PROC PROC_GetAllDanhMuc
AS 
SELECT * FROM DANHMUC

CREATE PROC PROC_GetAllDoiTuong
AS 
SELECT * FROM DOITUONG


--GET THEO ID --

CREATE PROC PROC_GetBaiTapbyID(@ID_baitap INT)
AS 
SELECT * FROM BAITAP WHERE ID_BAITAP=@ID_baitap


CREATE PROC PROC_GetDoiTuongbyTen(@Tendoituong nvarchar(50))
AS 
SELECT * FROM DOITUONG WHERE TENDOITUONG=@Tendoituong


CREATE PROC PROC_GetDanhMucbyTen(@Tendanhmuc nvarchar(50))
AS 
SELECT * FROM DANHMUC WHERE TENDANHMUC=@Tendanhmuc


--GET THEO DOI TUONG --
CREATE PROC PROC_GetBaiTapChoNguoiMoi
AS 
SELECT * FROM BAITAP, DOITUONG WHERE BAITAP.TENDOITUONG = DOITUONG.TENDOITUONG AND ID_DOITUONG = 1


CREATE PROC PROC_GetAllBaiTapTrungBinh
AS 
SELECT * FROM BAITAP where TENDOITUONG = 'TRUNG BÌNH'


CREATE PROC PROC_GetAllBaiTapNangCao
AS 
SELECT * FROM BAITAP where TENDOITUONG = 'NÂNG CAO'


CREATE PROC PROC_GetBaiTapTaiNha
AS 
SELECT * FROM BAITAP, DOITUONG WHERE BAITAP.TENDOITUONG = DOITUONG.TENDOITUONG AND ID_DOITUONG = 4


--GETHINHANH--
CREATE PROC PROC_GetAllHinhAnh
AS 
SELECT * FROM HINHANH 

--GETBAITAPHOT--
CREATE PROC PROC_GetBaiTapBung
AS 
SELECT * FROM BAITAP, DANHMUC WHERE BAITAP.TENDANHMUC = DANHMUC.TENDANHMUC AND ID_DANHMUC = 1

CREATE PROC PROC_GetBaiTapChan
AS 
SELECT * FROM BAITAP, DANHMUC WHERE BAITAP.TENDANHMUC = DANHMUC.TENDANHMUC AND ID_DANHMUC = 2

CREATE PROC PROC_GetBaiTapTay
AS 
SELECT * FROM BAITAP, DANHMUC WHERE BAITAP.TENDANHMUC = DANHMUC.TENDANHMUC AND ID_DANHMUC = 3

CREATE PROC PROC_GetBaiTapNguc
AS 
SELECT * FROM BAITAP, DANHMUC WHERE BAITAP.TENDANHMUC = DANHMUC.TENDANHMUC AND ID_DANHMUC = 4



--GETTHOILUONGBYID--
CREATE PROC PROC_GetThoiLuongById(@ID_baitap INT)
AS 
SELECT THOILUONG FROM BAITAP WHERE ID_BAITAP=@ID_baitap

SELECT THOILUONG FROM BAITAP WHERE ID_BAITAP=2

INSERT INTO DANHMUC (ID_DANHMUC,TENDANHMUC,MOTADANHMUC) VALUES 
(1,N'TẬP BỤNG', N'Các bài tập giúp săn chắc vùng bụng.'),
(2,N'TẬP CHÂN', N'Các bài tập giúp săn chắc vùng cơ bắp chân.'),
(3,N'TẬP TAY', N'Các bài tập giúp săn chắc vùng cơ cánh tay.'),
(4,N'TẬP NGỰC', N'Các bài tập giúp săn chắc vùng ngực.')

SELECT * FROM DANHMUC

INSERT INTO DOITUONG (ID_DOITUONG,TENDOITUONG,MOTADOITUONG) VALUES 
(1,N',MỚI BẮT ĐẦU', N'Các bài tập dành cho người mới bắt đầu tập.'),
(2,N'TRUNG BÌNH', N'Các bài tập ở mức trung bình.'),
(3,N'NÂNG CAO', N'Các bài tập nâng cao.'),
(4,N'TẠI NHÀ', N'Các bài tập giúp có thể tự tập ở nhà.')

SELECT * FROM DOITUONG

INSERT INTO BAITAP (ID_BAITAP,TENBAITAP,TENDOITUONG,TENDANHMUC,HINHANH,MOTABAITAP,THOILUONG,LUONGCALOTIEUTHU,TACDUNG) VALUES 
(1,N',BẬT NHẢY', N'MỚI BẮT ĐẦU',N'TẬP BỤNG', N'http://192.168.1.9/Images/test1.jpg',N'•Bắt đầu đứng 2 chân để gần nhau , tay buông xuống để 2 bên , sau đó nhảy lên chân dang ra và để hai tay lên cao trên đầu. trở lại vị trí bắt đầu rồi lặp lại.', 60,400,'•	Bài tập này tập uyện cho toàn thân và có tác dụng với tất cả nhóm cơ lớn'),
(2,N',GẬP BỤNG', N'MỚI BẮT ĐẦU',N'TẬP BỤNG', N'http://192.168.1.9/Images/test1.jpg',N'•Bắt đầu đứng 2 chân để gần nhau , tay buông xuống để 2 bên , sau đó nhảy lên chân dang ra và để hai tay lên cao trên đầu. trở lại vị trí bắt đầu rồi lặp lại.', 60,400,'•	Bài tập này tập uyện cho toàn thân và có tác dụng với tất cả nhóm cơ lớn'),
(3,N',GẬP BỤNG CHÉO', N'MỚI BẮT ĐẦU',N'TẬP BỤNG', N'http://192.168.1.9/Images/test1.jpg',N'•Bắt đầu đứng 2 chân để gần nhau , tay buông xuống để 2 bên , sau đó nhảy lên chân dang ra và để hai tay lên cao trên đầu. trở lại vị trí bắt đầu rồi lặp lại.', 60,400,'•	Bài tập này tập uyện cho toàn thân và có tác dụng với tất cả nhóm cơ lớn')

SELECT * FROM BAITAP