use WEBAPI

CREATE TABLE DANHMUC(
	ID_DANHMUC INT NOT NULL PRIMARY KEY,
	TENDANHMUC NVARCHAR(50) NOT NULL,
	MOTADANHMUC NVARCHAR(200) ,
)

CREATE TABLE DOITUONG(
	ID_DOITUONG INT PRIMARY KEY,
	TENDOITUONG NVARCHAR(20),
	)

CREATE TABLE BAITAP(
	ID_BAITAP INT NOT NULL PRIMARY KEY,
	TENBAITAP NVARCHAR(100) NOT NULL,
	ID_DANHMUC INT,
	ID_DOITUONG INT,
	HINHANH NVARCHAR(MAX),
	MOTABAITAP NVARCHAR(MAX),
	THOILUONG INT,
	LUONGCALOTIEUTHU INT,
	TACDUNG NVARCHAR(200),
	CONSTRAINT FK_BT_TENDANHMUC FOREIGN KEY (ID_DANHMUC) REFERENCES DANHMUC (ID_DANHMUC),
	CONSTRAINT FK_BT_TENDOITUONG FOREIGN KEY (ID_DOITUONG) REFERENCES DOITUONG (ID_DOITUONG),
)


CREATE TABLE USERACCOUNT(
	ID_USER INT NOT NULL PRIMARY KEY,
	USERNAME NVARCHAR(20),
	PASS_WORD NVARCHAR(20),
	EMAIL NVARCHAR(50),
)

INSERT INTO BAITAP (TENBAITAP, ID_BAITAP, ID_DANHMUC,ID_DOITUONG, MOTABAITAP,HINHANH, THOILUONG, LUONGCALOTIEUTHU) VALUES
('TAP BUNG',1,1,1,' TAP  BUNG ', N'http://192.168.1.9/webapiApp/Images/test1.jpg',300,20),
('TAP BUNG CO',2,2,2,' TAP  BUNG ', N'http://192.168.1.9/webapiApp/Images/test1.jpg',300,20),
('TAP BUNG CO',3,2,2,' TAP  BUNG ', N'http://192.168.1.9/webapiApp/Images/test1.jpg',300,20),
('TAP BUNG CO',4,2,2,' TAP  BUNG ', N'http://192.168.1.9/webapiApp/Images/test1.jpg',300,20),
('TAP BUNG CO',5,2,2,' TAP  BUNG ', N'http://192.168.1.9/webapiApp/Images/test1.jpg',300,20),





--GET TAT CA--
CREATE PROC PROC_GetAllBaiTap
AS 
SELECT * FROM BAITAP

CREATE PROC PROC_GetAllDanhMuc
AS 
SELECT * FROM DANHMUC

CREATE PROC PROC_GetAllDoiTuong
AS 
SELECT * FROM DOITUONG

CREATE PROC PROC_GetAllUser
AS 
SELECT * FROM USERACCOUNT



--GET THEO ID --

CREATE PROC PROC_GetBaiTapbyID(@ID_baitap INT)
AS 
SELECT * FROM BAITAP WHERE ID_BAITAP=@ID_baitap


CREATE PROC PROC_GetDoiTuongbyID(@ID_doituong INT)
AS 
SELECT * FROM DOITUONG WHERE ID_DOITUONG=@ID_doituong


CREATE PROC PROC_GetDanhMucbyID(@ID_danhmuc INT)
AS 
SELECT * FROM DANHMUC WHERE ID_DANHMUC=@ID_danhmuc


--GET THEO DOI TUONG --
CREATE PROC PROC_GetAllBaiTapChoNguoiMoi
AS 
SELECT * FROM BAITAP where ID_DOITUONG = 1


CREATE PROC PROC_GetAllBaiTapTrungBinh
AS 
SELECT * FROM BAITAP where ID_DOITUONG = 2


CREATE PROC PROC_GetAllBaiTapNangCao
AS 
SELECT * FROM BAITAP where ID_DOITUONG = 3


CREATE PROC PROC_GetAllBaiTapTaiNha
AS 
SELECT * FROM BAITAP where ID_DOITUONG = 4


--GETBAITAPHOT--
CREATE PROC PROC_GetBTPhanBung
AS 
SELECT * FROM BAITAP where ID_DANHMUC = 1

CREATE PROC PROC_GetBTPhanChan
AS 
SELECT * FROM BAITAP where ID_DANHMUC = 2


CREATE PROC PROC_GetBTPhanTay
AS 
SELECT * FROM BAITAP where ID_DANHMUC = 3

CREATE PROC PROC_GetBTPhanNguc
AS 
SELECT * FROM BAITAP where ID_DANHMUC = 4





